language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-mailgun.gemspec
- gem install sensu-plugins-mailgun-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: q0XlAu/K3gEVLPPIxDSsSq8FFfUFfTYp0x9qZjBxs/klcFW4Bs6SJu89dEflaLSp30YImfE4maHA17z6XSvHjh8faOksJjbrgdujAUPn+i43cQMAsm4HSmTPACC8igSAhi6MwU3yDb6v3rxXbiv6ltPe9ZPhwpMCW7m6t7MY6PQgHitOxVKGTXVxg2jqexMsXy1f2qajE6y23MMXqmv+bKUpGdp64B5AhlJgSGos/ViqHQ3u7X0F8fI1aNAbh+uvRaHsmvDI7hU9hmxHlI9gTX7+7L7kwjN3CkF54vxwHj7m7uanxeTCWwYCGEyGsCEdz/bV2K+qW0yKeckJ5qeD+KlLpE8vXS76Bg9tXIUvu7K2ChsfMahqKf+TH484WDO7ySb0yG15SiO2SiZFzAsALzE4fyHFkFLEq2dflRyOuvTgR8Pgmxjhc19dH9fTo8MJqvW3sY6D4inQIa7wMAqSbAw5UK76moH7mmqwE7adEQxBYX2So1Q4ASB3eJ4RPNo+rk1H36yqY7pMNGBfbu2EC6+G/XiNTMUGAT+DLk7+th0NVN8SykUruPSXq4TWk6YljkVzLfU6xChiisIliZTXBYtydcGaVjKiT/sEFvdGcrEXCypM0bgQTNZ/pNNX+GkejBhsmhw8mYgSLF7GZ2bm4FPRxpWqIaFie97eHIPJqng=
  gem: sensu-plugins-mailgun
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-mailgun
